version: '3'
services:
  app:
    build:
      context: .
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - 8100:8000
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:5.6.36
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=k8s
      - MYSQL_USER=k8s
      - MYSQL_PASSWORD=r00t
    ports:
      - 3340:3306
