apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: kigsmtua/smyllo:latest
        imagePullPolicy: Always
        command: ["bash"]
        args: ["-c", "./worker.sh"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "smyllo.settings"
        - name: C_FORCE_ROOT
          value: "true"
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
